title: Plateforme de Protection des Lanceurs d'Alerte en Afrique
email: info@pplaaf.org
url: "https://pplaaf.org"

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

collections_dir: collections
collections:
  board-en:
  board-fr:
  board-pt:
  management-en:
  management-fr:
  management-pt:
  ngos-en:
  ngos-fr:
  profiles-fr:
    output: true
    permalink: fr/:name.html
  profiles-pt:
    output: true
    permalink: pt/:name.html
  profiles-en:
    output: true
    permalink: :name.html
  studies-en:
    output: true
    permalink: :name.html
  studies-fr:
    output: true
    permalink: fr/:name.html

  
# Assets configuration
assets:
  compress:
    css: true
    js: true
  digest: true
  sources:
    - assets/img
    - assets/js
    - assets/css